function main(config) {
  config["proxy-groups"] = [
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Static.png",
      name: "🚀 节点选择",
      type: "select",
      proxies: ["♻️ 自动选择", "🇭🇰 香港", "🇨🇳 台湾", "🇸🇬 新加坡", "🇯🇵 日本", "🇺🇲 美国", "🇰🇷 韩国", "🔁 手动切换", "🌐 其他", "DIRECT"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Urltest.png",
      "include-all": true,
      "exclude-filter": "(?i)Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      name: "♻️ 自动选择",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Global.png",
      name: "⭕ 其他",
      type: "select",
      proxies: ["🚀 节点选择", "♻️ 自动选择", "DIRECT", "🇭🇰 香港", "🇨🇳 台湾", "🇸🇬 新加坡", "🇯🇵 日本", "🇺🇲 美国", "🇰🇷 韩国", "🔁 手动切换"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Game.png",
      name: "🕹 Game",
      type: "select",
      proxies: ["🔁 手动切换", "DIRECT"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Telegram.png",
      name: "📲 Telegram",
      type: "select",
      proxies: ["🚀 节点选择", "♻️ 自动选择", "🇸🇬 新加坡", "🇭🇰 香港", "🇨🇳 台湾", "🇯🇵 日本", "🇺🇲 美国", "🇰🇷 韩国", "🔁 手动切换", "DIRECT"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Spotify.png",
      name: "🎵 Spotify",
      type: "select",
      proxies: ["🚀 节点选择", "♻️ 自动选择", "🇸🇬 新加坡", "🇭㉚ 香港", "🇨🇳 台湾", "🇯🇵 日本", "🇺🇲 美国", "🇰🇷 韩国", "🔁 手动切换", "DIRECT"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/YouTube.png",
      name: "📹 YouTube",
      type: "select",
      proxies: ["🚀 节点选择", "♻️ 自动选择", "🇸🇬 新加坡", "🇭㉚ 香港", "🇨🇳 台湾", "🇯🇵 日本", "🇺🇲 美国", "🇰🇷 韩国", "🔁 手动切换", "DIRECT"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/TikTok.png",
      name: "🎶 TikTok",
      type: "select",
      proxies: ["🚀 节点选择", "♻️ 自动选择", "🇸㉚ 新加坡", "🇭㉚ 香港", "🇨🇳 台湾", "🇯㉚ 日本", "🇺㉚ 美国", "🇰㉚ 韩国", "🔁 手动切换", "DIRECT"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/TW.png",
      name: "📺 巴哈姆特",
      type: "select",
      proxies: ["🇨🇳 台湾", "🇭㉚ 香港", "🚀 节点选择", "🔁 手动切换", "DIRECT"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Bilibili.png",
      name: "📺 哔哩哔哩",
      type: "select",
      proxies: ["DIRECT", "🇨㉚ 台湾", "🇭㉚ 香港", "🔁 手动切换"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Global.png",
      name: "🌍 国外媒体",
      type: "select",
      proxies: ["🚀 节点选择", "♻️ 自动选择", "🇭㉚ 香港", "🇨㉚ 台湾", "🇸㉚ 新加坡", "🇯㉚ 日本", "🇺㉚ 美国", "🇰㉚ 韩国", "🔁 手动切换", "DIRECT"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/CN.png",
      name: "🐼 国内媒体",
      type: "select",
      proxies: ["DIRECT", "🇭㉚ 香港", "🇨㉚ 台湾", "🇸㉚ 新加坡", "🇯㉚ 日本", "🔁 手动切换"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Bing.png",
      name: "Ⓜ️ Bing",
      type: "select",
      proxies: ["DIRECT", "🚀 节点选择", "🇺㉚ 美国", "🇭㉚ 香港", "🇨㉚ 台湾", "🇸㉚ 新加坡", "🇯㉚ 日本", "🇰㉚ 韩国", "🔁 手动切换"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Microsoft.png",
      name: "Ⓜ️ 微软",
      type: "select",
      proxies: ["DIRECT", "🚀 节点选择", "🇺㉚ 美国", "🇭㉚ 香港", "🇨㉚ 台湾", "🇸㉚ 新加坡", "🇯㉚ 日本", "🇰㉚ 韩国", "🔁 手动切换"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Apple.png",
      name: "🍎 Apple",
      type: "select",
      proxies: ["DIRECT", "🚀 节点选择", "🇺㉚ 美国", "🇭㉚ 香港", "🇨㉚ 台湾", "🇸㉚ 新加坡", "🇯㉚ 日本", "🇰㉚ 韩国", "🔁 手动切换"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Game.png",
      name: "🎮 游戏平台",
      type: "select",
      proxies: ["DIRECT", "🚀 节点选择", "🇺㉚ 美国", "🇭㉚ 香港", "🇨㉚ 台湾", "🇸㉚ 新加坡", "🇯㉚ 日本", "🇰㉚ 韩国", "🔁 手动切换"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Google.png",
      name: "📢 谷歌FCM",
      type: "select",
      proxies: ["DIRECT", "🚀 节点选择", "🇺㉚ 美国", "🇭㉚ 香港", "🇨㉚ 台湾", "🇸㉚ 新加坡", "🇯㉚ 日本", "🇰㉚ 韩国", "🔁 手动切换"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Direct.png",
      name: "🔗 直连",
      type: "select",
      proxies: ["DIRECT", "🚀 节点选择", "♻️ 自动选择"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Reject.png",
      name: "⛔ 拦截",
      type: "select",
      proxies: ["REJECT", "DIRECT"],
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/HK.png",
      "include-all": true,
      "exclude-filter": "(?i)Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "(?i)港|HK|hk|Hong Kong|HongKong|hongkong|🇭㉚",
      name: "🇭㉚ 香港",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/JP.png",
      "include-all": true,
      "exclude-filter": "(?i)Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "(?i)日本|东京|東京都|大阪|泉日|埼玉|[^-]日|JP|Japan|🇯㉚",
      name: "🇯㉚ 日本",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/US.png",
      "include-all": true,
      "exclude-filter": "(?i)Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "(?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|SFO|NYC|Oregon|United States|🇺㉚",
      name: "🇺㉚ 美国",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/TW.png",
      "include-all": true,
      "exclude-filter": "(?i)Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "(?i)台|新北|彰化|TW|Taiwan|🇨㉚",
      name: "🇨㉚ 台湾",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/SG.png",
      "include-all": true,
      "exclude-filter": "(?i)Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "(?i)新加坡|坡|狮城|SG|Singapore|🇸㉚",
      name: "🇸㉚ 新加坡",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/KR.png",
      "include-all": true,
      "exclude-filter": "(?i)Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "(?i)KR|Korea|KOR|首尔|韩|韓|🇰㉚",
      name: "🇰㉚ 韩国",
      type: "url-test",
      interval: 300,
    },
    {
      icon: "https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Global.png",
      "include-all": true,
      "exclude-filter": "(?i)Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置",
      filter: "^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|日本|东京|日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|SFO|NYC|Oregon|United States|台|中华民国|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|KR|Korea|KOR|首尔|韩|韓)).*$",
      name: "🌐 其他",
      type: "select",
    }
  ];

  if (!config['rule-providers']) {
    config['rule-providers'] = {};
  }
  config["rule-providers"] = Object.assign(config["rule-providers"], {
    "game": {
      url: "https://raw.githubusercontent.com/J54264/rules/main/proxy/Game.list",
      path: "./ruleset/game.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "proxy": {
      url: "https://raw.githubusercontent.com/J54264/rules/main/proxy/Proxy.list",
      path: "./ruleset/proxy.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "direct": {
      url: "https://raw.githubusercontent.com/J54264/rules/main/proxy/Direct.list",
      path: "./ruleset/direct.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "local_area_network": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list",
      path: "./ruleset/local_area_network.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "unban": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list",
      path: "./ruleset/unban.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "reject": {
      url: "https://raw.githubusercontent.com/J54264/rules/main/proxy/Reject.list",
      path: "./ruleset/reject.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "adblock4limbo": {
      url: "https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo.list",
      path: "./ruleset/adblock4limbo.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "ban_ad": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list",
      path: "./ruleset/ban_ad.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "ban_program_ad": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list",
      path: "./ruleset/ban_program_ad.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "google_fcm": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list",
      path: "./ruleset/google_fcm.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "google_cn": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list",
      path: "./ruleset/google_cn.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "steam_cn": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list",
      path: "./ruleset/steam_cn.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "bing": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list",
      path: "./ruleset/bing.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "microsoft": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list",
      path: "./ruleset/microsoft.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "apple": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list",
      path: "./ruleset/apple.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "tiktok": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list",
      path: "./ruleset/tiktok.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "telegram": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list",
      path: "./ruleset/telegram.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "epic": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list",
      path: "./ruleset/epic.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "ea": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list",
      path: "./ruleset/ea.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "sony": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list",
      path: "./ruleset/sony.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "steam": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list",
      path: "./ruleset/steam.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "nintendo": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list",
      path: "./ruleset/nintendo.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "spotify": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list",
      path: "./ruleset/spotify.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "youtube": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list",
      path: "./ruleset/youtube.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "bahamut": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list",
      path: "./ruleset/bahamut.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "bilibili_hmt": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list",
      path: "./ruleset/bilibili_hmt.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "bilibili": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list",
      path: "./ruleset/bilibili.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "china_media": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list",
      path: "./ruleset/china_media.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "global_media": {
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list",
      path: "./ruleset/global_media.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "ip_test": {
      url: "https://raw.githubusercontent.com/liandu2024/clash/main/Check.list",
      path: "./ruleset/ip_test.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "china_domain": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list",
      path: "./ruleset/china_domain.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "china_company_ip": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list",
      path: "./ruleset/china_company_ip.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    },
    "download": {
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list",
      path: "./ruleset/download.yaml",
      behavior: "classical",
      interval: 86400,
      format: "yaml",
      type: "http",
    }
  });

  config["rules"] = [
    "RULE-SET,game,🕹 Game",
    "RULE-SET,proxy,🚀 节点选择",
    "RULE-SET,direct,🔗 直连",
    "RULE-SET,local_area_network,🔗 直连",
    "RULE-SET,unban,🔗 直连",
    "RULE-SET,reject,⛔ 拦截",
    "RULE-SET,adblock4limbo,⛔ 拦截",
    "RULE-SET,ban_ad,⛔ 拦截",
    "RULE-SET,ban_program_ad,⛔ 拦截",
    "RULE-SET,google_fcm,📢 谷歌FCM",
    "RULE-SET,google_cn,🔗 直连",
    "RULE-SET,steam_cn,🔗 直连",
    "RULE-SET,bing,Ⓜ️ Bing",
    "RULE-SET,microsoft,Ⓜ️ 微软",
    "RULE-SET,apple,🍎 Apple",
    "RULE-SET,tiktok,🎶 TikTok",
    "RULE-SET,telegram,📲 Telegram",
    "RULE-SET,epic,🎮 游戏平台",
    "RULE-SET,ea,🎮 游戏平台",
    "RULE-SET,sony,🎮 游戏平台",
    "RULE-SET,steam,🎮 游戏平台",
    "RULE-SET,nintendo,🎮 游戏平台",
    "RULE-SET,spotify,🎵 Spotify",
    "RULE-SET,youtube,📹 YouTube",
    "RULE-SET,bahamut,📺 巴哈姆特",
    "RULE-SET,bilibili_hmt,📺 哔哩哔哩",
    "RULE-SET,bilibili,📺 哔哩哔哩",
    "RULE-SET,china_media,🐼 国内媒体",
    "RULE-SET,global_media,🌍 国外媒体",
    "RULE-SET,ip_test,🚀 节点选择",
    "RULE-SET,china_domain,🔗 直连",
    "RULE-SET,china_company_ip,🔗 直连",
    "RULE-SET,download,🔗 直连",
    "GEOIP,CN,🔗 直连",
    "MATCH,⭕ 其他"
  ];

  return config;
}
