name: Build Rules

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '32 18 * * *'  # 每天 UTC 18:32（北京时间 2:32）触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. 检出目标仓库 J54264/rules
      - name: Checkout J54264/rules repository
        uses: actions/checkout@v4
        with:
          repository: J54264/rules
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      # 2. 设置环境变量
      - name: Set variables
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "REPODIR=$PWD" >> $GITHUB_ENV

      # 3. 克隆 limbopro/Adblock4limbo 并提取 Adblock4limbo.list
      - name: Clone limbopro/Adblock4limbo and copy Adblock4limbo.list
        run: |
          git clone https://github.com/limbopro/Adblock4limbo.git
          mkdir -p ./proxy  # 确保 proxy 目录存在
          cp Adblock4limbo/Adblock4limbo.list ./proxy/

      # 4. 启动 subconverter 服务
      - name: Background run subconverter
        run: |
          curl -s https://api.github.com/repos/tindy2013/subconverter/releases \
            | grep "browser_download_url.*subconverter_linux64.tar.gz" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q
          tar -xf subconverter_linux64.tar.gz
          ./subconverter/subconverter &
          python3 -m http.server 8080 --bind 127.0.0.1 --directory './proxy/' &

      # 5. 启动 mihomo 服务
      - name: Background run mihomo
        run: |
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
            | grep "browser_download_url.*mihomo-linux-amd64-alpha.*.deb" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q -O mihomo-linux-amd64-alpha.deb
          sudo apt install --fix-missing ./mihomo-linux-amd64-alpha.deb
          /usr/bin/mihomo &

      # 6. 执行转换脚本
      - name: Start convert
        run: |
          chmod +x ./script/convert.sh
          ./script/convert.sh

      # 7. 提交并推送更改
      - name: Commit and Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "${{ env.BUILDTIME }} rules conversion"
            git push origin main
          else
            echo "No changes to commit"
          fi
