name: Generate Proxy Rules

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy proxy folder from J54264/rules
        run: |
          mkdir -p temp/rules/proxy
          cp -r proxy/*.list temp/rules/proxy/

      - name: Sparse checkout limbopro/Adblock4limbo for Adblock4limbo.list
        run: |
          mkdir -p temp/rules/proxy
          git init temp/limbopro
          cd temp/limbopro
          git remote add origin https://github.com/limbopro/Adblock4limbo.git
          git config core.sparseCheckout true
          echo "Adblock4limbo.list" > .git/info/sparse-checkout
          git pull --depth 1 origin main
          cp Adblock4limbo.list ../../temp/rules/proxy/
          cd ../..

      - name: Background run subconverter
        run: |
          curl -s https://api.github.com/repos/tindy2013/subconverter/releases \
            | grep "browser_download_url.*subconverter_linux64.tar.gz" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q
          tar -xf subconverter_linux64.tar.gz
          ./subconverter/subconverter &
          python3 -m http.server 8080 --bind 127.0.0.1 --directory './temp/rules/' &

      - name: Install mihomo
        run: |
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
            | grep "browser_download_url.*mihomo-linux-amd64" \
            | grep -v "go" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q -O mihomo.gz
          gunzip mihomo.gz
          chmod +x mihomo

      - name: Start convert
        run: |
          chmod +x ./convert.sh
          ./convert.sh

      - name: Move generated files to providers directory
        run: |
          mkdir -p rules/proxy/providers
          if ls temp/rules/proxy/*_Domain.yaml temp/rules/proxy/*_IP.yaml temp/rules/proxy/*_Domain.mrs temp/rules/proxy/*_IP.mrs 2>/dev/null; then
            mv temp/rules/proxy/*_Domain.yaml temp/rules/proxy/*_IP.yaml temp/rules/proxy/*_Domain.mrs temp/rules/proxy/*_IP.mrs rules/proxy/providers/
          else
            echo "No matching files found in temp/rules/proxy/"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add rules/proxy/providers/*
          git commit -m "Update proxy rules" || echo "No changes to commit"
          git push
