name: Build Rules

on:
  workflow_dispatch:
  schedule:
    - cron: '32 18 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout J54264/rules repository
        uses: actions/checkout@v4
        with:
          repository: J54264/rules
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Set variables
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "REPODIR=$PWD" >> $GITHUB_ENV

      - name: Clean up submodule residuals
        run: |
          git rm -f Adblock4limbo || true
          rm -rf .gitmodules Adblock4limbo

      - name: Fetch Adblock4limbo.list
        run: |
          mkdir -p ./proxy
          wget -q -O ./proxy/Adblock4limbo.list https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo.list

      # 添加调试步骤：检查 .list 文件内容
      - name: Debug list files
        run: |
          echo "Listing proxy directory contents:"
          ls -l ./proxy/
          echo "Contents of .list files:"
          find ./proxy -name "*.list" -exec echo "File: {}" \; -exec cat {} \;

      - name: Background run subconverter
        run: |
          curl -s https://api.github.com/repos/tindy2013/subconverter/releases \
            | grep "browser_download_url.*subconverter_linux64.tar.gz" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q -P /tmp/
          tar -xf /tmp/subconverter_linux64.tar.gz -C /tmp/
          /tmp/subconverter/subconverter &
          python3 -m http.server 8080 --bind 127.0.0.1 --directory './proxy/' &

      - name: Background run mihomo
        run: |
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
            | grep "browser_download_url.*mihomo-linux-amd64-alpha.*.deb" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q -O /tmp/mihomo-linux-amd64-alpha.deb
          sudo apt install --fix-missing /tmp/mihomo-linux-amd64-alpha.deb
          /usr/bin/mihomo &

      - name: Start convert
        run: |
          chmod +x ./script/convert.sh
          ./script/convert.sh

      # 添加调试步骤：检查生成的文件
      - name: Debug generated files
        run: |
          echo "Generated files in proxy/providers:"
          ls -l ./proxy/providers/ || echo "No files generated"

      - name: Clean up temporary files
        run: |
          rm -rf /tmp/subconverter /tmp/mihomo-linux-amd64-alpha.deb /tmp/subconverter_linux64.tar.gz
          rm -f ./proxy/Adblock4limbo.list

      - name: Commit and Push Changes
        run: |
          git add .
          if git status --porcelain | grep -q .; then
            git commit -m "${{ env.BUILDTIME }} rules conversion"
            git push origin main
          else
            echo "No changes to commit"
          fi
