name: Build rules

on:
  workflow_dispatch:
  # 每天 2:32 (UTC+8) 触发一次
  schedule:
    - cron: '32 18 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 步骤1：检出主仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 步骤2：设置全局变量，包括构建时间和仓库目录
      - name: Set variables
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "REPODIR=$PWD" >> $GITHUB_ENV

      # 步骤3：克隆 J54264/rules 和 limbopro/Adblock4limbo 仓库
      - name: Clone repositories
        run: |
          git clone https://github.com/J54264/rules.git
          git clone https://github.com/limbopro/Adblock4limbo.git

      # 步骤4：下载并后台运行 subconverter
      - name: Background run subconverter
        run: |
          curl -s https://api.github.com/repos/tindy2013/subconverter/releases \
            | grep "browser_download_url.*subconverter_linux64.tar.gz" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q
          tar -xf subconverter_linux64.tar.gz
          ./subconverter/subconverter &
          python3 -m http.server 8080 --bind 127.0.0.1 --directory './rule/' &

      # 步骤5：下载并后台运行 mihomo
      - name: Background run mihomo
        run: |
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
            | grep "browser_download_url.*mihomo-linux-amd64-alpha.*.deb" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q -O mihomo-linux-amd64-alpha.deb
          sudo apt install --fix-missing ./mihomo-linux-amd64-alpha.deb
          /usr/bin/mihomo &

      # 步骤6：执行转换脚本
      - name: Start conversion
        run: |
          chmod +x ./script/convert.sh
          ./script/convert.sh

      # 步骤7：提交并推送更改
      - name: Commit and Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "${{ env.BUILDTIME }} for rules"
            git push origin master
          else
            echo "No changes to commit"
          fi

      # 步骤8：清理克隆的仓库
      - name: Clean up cloned repositories
        run: |
          rm -rf rules
          rm -rf Adblock4limbo
