name: Sync Rules

于:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # UTC+8 每天 0 点

jobs:
  convert-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup directories
        run: |
          mkdir -p proxy/providers/{J54264,limbopro}
          sudo apt-get update && sudo apt-get install -y jq yq

      # 启动 subconverter 后台服务
      - name: Run subconverter
        run: |
          wget -q $(curl -s https://api.github.com/repos/tindy2013/subconverter/releases/latest | grep "browser_download_url.*linux64.tar.gz" | cut -d '"' -f4)
          tar -xzf subconverter_linux64.tar.gz
          ./subconverter/subconverter &
          sleep 10  # 等待服务启动

      # 启动 Mihomo 环境
      - name: Run Mihomo
        run: |
          wget -qO mihomo.deb $(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | grep "browser_download_url.*linux-amd64" | cut -d '"' -f4)
          sudo dpkg -i mihomo.deb || true
          sudo apt-get install -f -y
          /usr/bin/mihomo &

      # 规则下载与转换
      - name: Process rules
        run: |
          # 下载 J54264 规则
          git clone --depth=1 --branch=main https://github.com/J54264/rules.git tmp/J54264
          cp tmp/J54264/proxy/*.list ./proxy/providers/J54264/

          # 下载 limbopro 规则
          wget -q -P proxy/providers/limbopro/ https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/*.list

          # 执行转换脚本
          chmod +x scripts/convert_rules.sh
          ./scripts/convert_rules.sh

      # 提交变更
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add proxy/providers/
          git commit -m "Auto-update rules $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
