name: Convert Rules

# 事件触发器部分 (必须存在)
于:
  # 手动触发选项
  workflow_dispatch:
  # 每日UTC时间16:00（北京时间0点）自动运行
  schedule:
    - cron: '0 16 * * *'

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup directories
      run: mkdir -p ./proxy/providers

    - name: Fetch external rules
      run: |
        wget -q -O ./proxy/providers/Adblock4limbo.list \
        https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo.list

    - name: Start Subconverter
      run: |
        # 下载并启动 subconverter
        curl -s https://api.github.com/repos/tindy2013/subconverter/releases \
          | grep "browser_download_url.*subconverter_linux64.tar.gz" \
          | head -n 1 | cut -d '"' -f 4 | xargs wget -q
        tar -xf subconverter_linux64.tar.gz
        ./subconverter/subconverter &
        python3 -m http.server 8080 --directory ./proxy/providers/ &

    - name: Install Mihomo
      run: |
        # 安装 Mihomo (amd64 架构)
        curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
          | grep "browser_download_url.*mihomo-linux-amd64.*\.deb" \
          | head -n 1 | cut -d '"' -f 4 | xargs wget -qO mihomo.deb
        sudo dpkg --force-all -i mihomo.deb || true
        /usr/bin/mihomo &

    - name: Convert rules
      run: |
        chmod +x ./script/convert.sh
        ./script/convert.sh

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./proxy/providers
        git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M')"
        git push
