name: Convert Rules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # UTC时间16:00=北京时间0:00

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare directories
      run: |
        mkdir -p ./proxy/providers
        
    - name: Get external rules
      run: |
        wget -q -O ./proxy/Adblock4limbo.list \
        https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo.list

    - name: Start Subconverter
      run: |
        curl -s https://api.github.com/repos/tindy2013/subconverter/releases \
          | grep "browser_download_url.*subconverter_linux64.tar.gz" \
          | head -n 1 | cut -d '"' -f 4 | xargs wget -q
        tar -xf subconverter_linux64.tar.gz
        ./subconverter/subconverter &
        timeout 30 bash -c 'until curl -sf http://127.0.0.1:25500; do sleep 1; done'
        python3 -m http.server 8080 --directory ./proxy/ &

    - name: Install Mihomo
      run: |
        curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
          | grep "browser_download_url.*mihomo-linux-amd64.*\.deb" \
          | head -n 1 | cut -d '"' -f 4 | xargs wget -qO mihomo.deb
        sudo dpkg --force-all -i mihomo.deb || true
        /usr/bin/mihomo &
        sleep 10

    - name: Convert rules
      run: |
        chmod +x ./script/convert.sh
        ./script/convert.sh

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./proxy/providers/*
        git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M') with YAML"
        git push
