name: Build rules

on:
  workflow_dispatch:  # Manual trigger
  # Runs daily at 2:32 AM (UTC+8), which is 18:32 UTC
  schedule:
    - cron: '32 18 * * *'
  push:
    branches:
      - main  # Assuming your default branch is 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow writing to the repository
    steps:
      # Step 1: Checkout your repository (J54264/rules)
      - name: Checkout J54264/rules repository
        uses: actions/checkout@v4
        with:
          repository: J54264/rules
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./rules  # Clone into './rules' directory

      # Step 2: Clone limbopro/Adblock4limbo repository
      - name: Clone limbopro/Adblock4limbo
        run: |
          git clone https://github.com/limbopro/Adblock4limbo.git ./Adblock4limbo

      # Step 3: Set up environment variables and Git configuration
      - name: Set variables
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "REPODIR=$PWD" >> $GITHUB_ENV

      # Step 4: Start subconverter in the background for rule conversion
      - name: Background run subconverter
        run: |
          curl -s https://api.github.com/repos/tindy2013/subconverter/releases \
            | grep "browser_download_url.*subconverter_linux64.tar.gz" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q
          tar -xf subconverter_linux64.tar.gz
          ./subconverter/subconverter &
          python3 -m http.server 8080 --bind 127.0.0.1 --directory './rules/proxy' &

      # Step 5: Start mihomo in the background for .mrs conversion
      - name: Background run mihomo
        run: |
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
            | grep "browser_download_url.*mihomo-linux-amd64-alpha.*.deb" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q -O mihomo-linux-amd64-alpha.deb
          sudo apt install --fix-missing ./mihomo-linux-amd64-alpha.deb
          /usr/bin/mihomo &

      # Step 6: Execute the conversion script
      - name: Start convert
        run: |
          chmod +x ./rules/script/convert.sh
          ./rules/script/convert.sh

      # Step 7: Commit and push changes to J54264/rules
      - name: Commit and Push Changes
        run: |
          cd ./rules
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "${{ env.BUILDTIME }} - Update rules"
            git push origin main
          else
            echo "No changes to commit"
          fi

      # Step 8: Clean up cloned repository and temporary files
      - name: Clean up
        run: |
          rm -rf ./Adblock4limbo  # Remove cloned Adblock4limbo repository
          rm -rf ./rules/proxy/*.list  # Remove original .list files after conversion
