name: Build rules

on:
  workflow_dispatch:
  schedule:
    - cron: '32 18 * * *'  # UTC时间18:32，对应UTC+8 2:32 [[1]][[6]]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 检出当前仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: J54264/rules  # 目标仓库路径 [[2]]
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 设置Git配置
      - name: Set Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 创建临时目录
      - name: Create temp directory
        run: mkdir -p temp/rules/proxy

      # 复制原始proxy文件
      - name: Copy proxy files
        run: cp -r proxy/*.list temp/rules/proxy/

      # 克隆Adblock4limbo并提取文件
      - name: Sparse checkout Adblock4limbo.list
        run: |
          mkdir -p temp/limbopro
          cd temp/limbopro
          git init
          git remote add origin https://github.com/limbopro/Adblock4limbo.git
          echo "/Adblock4limbo.list" > .git/info/sparse-checkout  # 添加路径前缀 [[7]]
          git config core.sparseCheckout true
          git pull --depth=1 origin main
          cp Adblock4limbo.list ../proxy/  # 确保路径正确 [[3]]

      # 启动Subconverter服务
      - name: Start Subconverter
        run: |
          wget -q https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
          tar -xf subconverter_linux64.tar.gz
          ./subconverter/subconverter -p 25690 &  # 明确指定默认端口 [[8]]
          sleep 5  # 等待服务启动

      # 启动Mihomo服务
      - name: Start Mihomo
        run: |
          wget -q -O mihomo.deb $(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases | grep 'browser_download_url.*linux-amd64.*.deb' | head -n1 | cut -d '"' -f4)
          sudo dpkg -i mihomo.deb || true
          /usr/bin/mihomo &

      # 执行转换脚本
      - name: Run convert.sh with debug
        env:
          BASE_URL: "http://127.0.0.1:25690"  # 与Subconverter端口一致 [[8]]
          LOCAL_DIR: "./temp/rules/proxy"
        run: |
          chmod +x ./script/convert.sh
          ./script/convert.sh
          ls -l $LOCAL_DIR  # 调试输出文件路径 [[4]]

      # 移动文件并清理
      - name: Move files and cleanup
        run: |
          mkdir -p rules/proxy/providers
          mv temp/rules/proxy/*_Domain.yaml temp/rules/proxy/*_IP.yaml temp/rules/proxy/*_Domain.mrs temp/rules/proxy/*_IP.mrs rules/proxy/providers/ || true  # 允许部分文件缺失 [[5]]
          rm -rf temp/

      # 提交变更
      - name: Commit and Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add --all
          git commit -m "Update at $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push origin main || echo "No changes to push" [[6]]
